spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/miniproject02
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: banticoke@gmail.com
    password: <APP PASSWORD>
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
   
